### ISSUE TITLE
Safe Zone issue with concealment 

### ISSUE THREAD

**Issue by ghost** [TorchAPI/Concealment#20]
It seems than when a grid is concealed, the safe zone block will stop consuming energy. 

However the timer will still continue to go to 0, after that when the safe zone hits 0 hour remaining time, it will not consume a new zone chip...

And of course the safe zone is still active even at 0 hour remaining time.

So there is no logs but I’m guessing it’s concealment that is the cause of this, I tested on an instance with only essentials and concealment installed, issue was there.

Good luck to fix and thank you :).

**Comment by LordTylus** [comment]
This is true we made the same observations on our server with Concealment

would be pretty neat to have the timer just pausing when grids concealed.

because the one of the major complains on our servers apart from not consuming the next chip is that stores are permanently low on chips so they wont be able to protect themselves over night.

whichprobably is our fault for having so many player slots in the first place
